### PR TITLE
fix marker-end rendering

### PR DESCRIPTION
**Pull request by yowmamasita**
Fix for:
https://github.com/gabelerner/canvg/issues/128
https://github.com/gabelerner/canvg/issues/294
https://github.com/gabelerner/canvg/issues/300
https://github.com/gabelerner/canvg/issues/308

### CODE REVIEW

**Comment by yowmamasita** [comment]
Still broken for rotated arrow heads

**Comment by yowmamasita** [comment]
Fixed for rotated arrow heads

**Comment by gabelerner** [comment]
@yowmamasita ...

this branch is still not quite perfect:
capture

but then again, neither is master:
capture2

it does look closer though, maybe i'll have some time to experiment soon

**Comment by yowmamasita** [comment]
You are correct, after several tests yesterday I did realize this is far from perfect. Thank you for testing

**Comment by gabelerner** [comment]
i have a branch open that should fix all marker issues ... should get it out soon

**Comment by NikitaSkoblov** [comment]
Hello! Any progress with fixing marker misplacement? I've ran into that issue as well.

**Pull request closed without merging**
