### PR TITLE
UMD-ify canvg, stackblur and rgbcolor

### PR DESCRIPTION
**Pull request by Rich-Harris**
Follow-up from https://github.com/Rich-Harris/canvg/issues/2 - this PR exports `canvg` (and by extension `stackBlur` and `RGBColor`) in a way that's compatible with CommonJS/AMD module loaders and optimisers

### CODE REVIEW

**Comment by gabelerner** [comment]
is https://github.com/gabelerner/canvg/pull/335 a good alternative?

**Comment by Rich-Harris** [comment]
The problem with #335 is that it still relies on adding everything to the global namespace, which is a bit old-school! It means that a) the global namespace gets polluted (not the end of the world, but it's best to avoid relying on globals if possible - someone could innocently assign `RGBColor` to something else, and canvg would fail), b) developers have to remember to include all three `<script>` tags, and c) it's incompatible with module systems.

By c) I mean that a developer wouldn't be able to do this:

```js
// In an ES6 module
import canvg from 'canvg';

// In an AMD module
define(['canvg'], function (canvg) {
  // ...
});

// In a CommonJS module
var canvg = require('canvg');
```

A huge number of apps are built with AMD and CommonJS (which thanks to node.js and [browserify](http://browserify.org/) is basically an interim standard, until ES6 modules are supported by browsers). The great thing about UMD is that it makes canvg available to everyone, regardless of whether they're using AMD, CommonJS or plain old `<script>` tags.

If you like, I can update this PR - an even easier situation for developers would be if the three modules were bundled up into a single distributable UMD file. The only build step that would be required is typing `npm run build`, and that would happen automatically on `npm publish`. Let me know if that's of interest.

**Comment by gabelerner** [comment]
thanks for the detailed response, i'll think about how to best transition and will let you know if i need more assistance

**Comment by MikeJoyce19** [comment]
hey @gabelerner . We're running into this problem using jspm and rgbcolor.js not being available. Any update on where this pull request stands?

**Comment by gabelerner** [comment]
i'll push it out this weekend!

**Comment by gabelerner** [comment]
@MikeJoyce19 @Rich-Harris can you guys review https://github.com/gabelerner/canvg/pull/375/files?w=1 please? I just merged the changes from this PR into that one and tested locally, seems to work.

**Comment by MikeJoyce19** [comment]
Confirmed. These changes are working for me using jspm module loader.  

Just an FYI, because rgbcolor.js and StackBlur.js are referred to as modules in canvg.js, the module loader thinks that these files are available at the root of your web app.  To get this to work, I created a map to both files:

```
System.config({
"map" : {
///some other maps
"rgbcolor" : "jspm_packages/github/gabelerner/canvg@master/rgbcolor",
 "stackblur" : "jspm_packages/github/gabelerner/canvg@master/StackBlur",
//more maps
}
})
```

I feel like there's a better way to do this, maybe using meta configuration to tell the module loader where the root of your package is in jspm_packages or npm.  If there is, I'd love to know.

Thanks Gabe

**Comment by Rich-Harris** [comment]
LGTM. I guess the 'better way' would be to publish StackBlur and rgbcolor as separate projects, and offer a pre-built version in this repo that bundles all three libraries. That way, it would 'just work' whether you're using script tags, JSPM, Browserify, whatever. Would be happy to help out with that as I want to be able to continue using canvg - let me know if that's of interest.

In the meantime, merging #375 won't stop anyone from being able to use canvg as they currently do (via script tags) and will mean that people using module loaders/bundlers will be able to use it, albeit with some configuration necessary in some cases.

**Comment by gabelerner** [comment]
merged #375 ... maybe the right idea is to convince the authors of stackblur/rgbcolor to put up github repos and umdify their projects?

**Pull request closed without merging**
